### ISSUE TITLE
feature: support logging with tracing crate.

### ISSUE THREAD

**Issue by dan-da** [PhilipDaniels/logging_timer#6]
In my app, all logging is done with the tracing crate.

Perhaps log and tracing could both be feature flags, and then one could output timer messages via log, tracing, or both.

**Comment by PhilipDaniels** [comment]
This crate specifically targets logging. Making it support the tracing infrastructure as well would mean basically duplicating the code, so I won't be doing this. Feel free to use the code as a basis for writing a 'tracing_timer' crate, if there isn't one already.
