### ISSUE TITLE
feature: disable logging below time threshold

### ISSUE THREAD

**Issue by dan-da** [PhilipDaniels/logging_timer#7]
from the wish-list dept:

Sometimes we may wish to log only outlier functions that are executing "slowly".  That way we don't clutter up the log with lots of timing for calls that are speedy.

It would be useful to have an option to only log events that exceed a given threshold duration, eg 0.1 seconds.

Also, it would be nice if that threshold value could somehow be defined for the entire crate, so one doesn't have to pass it as a param everywhere that #[time] is used.   Maybe an env variable would be useful for that, which can be [defaulted in Cargo.toml](https://doc.rust-lang.org/cargo/reference/config.html?highlight=%5Benv%5D#env).

**Comment by PhilipDaniels** [comment]
I think that would complicate the code quite a lot. I think that such analysis/requirement to filter is likely to be exploratory and varying as you understand your program more, which to me indicates that it should be left to downstream tools. You could even achieve something very simple just by piping the logs through ripgrep, or awk, or a few lines of python.
